// Malafrena 剧情成就系统数据

const plotAchievements = {
    // ============= PART_ONE: 童年与青年 (12个成就) =============
    'childhood_01': {
        'id': 'childhood_01',
        'title': '山谷中的童年',
        'title_cn': '山谷中的童年',
        'chapter': 'PART_ONE',
        'category': 'childhood',
        'description': 'Itale在Malafrena山谷中度过的童年时光，与妹妹Laura和表妹Piera一起成长',
        'description_cn': 'Itale在Malafrena山谷中度过的童年时光，与妹妹Laura和表妹Piera一起成长',
        'characters': ['itale', 'laura', 'piera', 'guide', 'eleonora'],
        'tags': ['童年', '家庭', '成长'],
        'evidence': 'In the valley of Malafrena, between the mountains, the Sorde estate lay like a green jewel in the cupped hand of the hills.',
        'evidence_cn': '在Malafrena的山谷中，群山之间，索尔德庄园就像 Hills 的手中握着的一颗绿宝石。'
    },
    'childhood_02': {
        'id': 'childhood_02',
        'title': 'Eleonora\'s Teaching',
        'title_cn': '埃莉奥诺拉的教育',
        'chapter': 'PART_ONE',
        'category': 'education',
        'description': '母亲Eleonora亲自教育Itale和Laura，培养他们对知识的渴望',
        'description_cn': '母亲埃莉奥诺拉亲自教育伊塔勒和劳拉，培养他们对知识的渴望',
        'characters': ['eleonora', 'itale', 'laura'],
        'tags': ['教育', '母爱', '知识'],
        'evidence': 'Eleonora taught both children until Itale was eleven and Laura eight, giving them the run of the library.',
        'evidence_cn': '埃莉奥诺拉一直教两个孩子，直到伊塔勒十一岁、劳拉八岁，让他们自由使用图书馆。'
    },
    'childhood_03': {
        'id': 'childhood_03',
        'title': 'The Library',
        'title_cn': '图书馆',
        'chapter': 'PART_ONE',
        'category': 'education',
        'description': 'Itale在庄园图书馆中发现政治哲学书籍，开始思考社会问题',
        'description_cn': '伊塔勒在庄园图书馆中发现政治哲学书籍，开始思考社会问题',
        'characters': ['itale', 'laura', 'eleonora'],
        'tags': ['知识', '启蒙', '政治'],
        'evidence': 'The library was a long room, dark even on the brightest days, with tall windows and shelves of books from floor to ceiling.',
        'evidence_cn': '图书馆是一个长房间，即使在最明亮的日子里也很昏暗，有着高大的窗户和从地板到天花板的书架。'
    },
    'childhood_04': {
        'id': 'childhood_04',
        'title': 'Piera\'s Arrival',
        'title_cn': '皮耶拉的到来',
        'chapter': 'PART_ONE',
        'category': 'family',
        'description': 'Piera的母亲去世后，Eleonora收养了这个两岁的侄女',
        'description_cn': '皮耶拉的母亲去世后，埃莉奥诺拉收养了这个两岁的侄女',
        'characters': ['piera', 'eleonora', 'itale', 'casu'],
        'tags': ['家庭', '收养', '童年'],
        'evidence': 'Piera\'s mother had died in childbed; her father Casu was a poor relation, a drunkard. Eleonora had taken charge of the two-year-old Piera at once.',
        'evidence_cn': '皮耶拉的母亲死于难产；她的父亲卡苏是个穷亲戚，一个酒鬼。埃莉奥诺拉立即承担起对两岁的皮耶拉的照顾。'
    },
    'childhood_05': {
        'id': 'childhood_05',
        'title': 'First Love',
        'title_cn': '初恋',
        'chapter': 'PART_ONE',
        'category': 'romance',
        'description': 'Itale对表妹Piera产生了朦胧的爱意',
        'description_cn': '伊塔勒对表妹皮耶拉产生了朦胧的爱意',
        'characters': ['itale', 'piera'],
        'tags': ['初恋', '青春', '纯真'],
        'evidence': 'Itale looked at Piera as she stood half turned from him and saw on the slender nape of her neck... three freckles: a pleasant sight.',
        'evidence_cn': '伊塔勒看着半转身对着他的皮耶拉，在她纤细的后颈上... 三颗雀斑：一个愉快的景象。'
    },
    'childhood_06': {
        'id': 'childhood_06',
        'title': 'Guide\'s Expectations',
        'title_cn': '吉德的期望',
        'chapter': 'PART_ONE',
        'category': 'family',
        'description': '父亲Guide期望Itale继承庄园，但Itale心怀更大的理想',
        'description_cn': '父亲吉德期望伊塔勒继承庄园，但伊塔勒心怀更大的理想',
        'characters': ['itale', 'guide', 'emanuel'],
        'tags': ['父子', '期望', '冲突'],
        'evidence': 'Guide Sorde expected his son to inherit the estate, but Itale dreamed of cities and universities, of the world beyond the mountains.',
        'evidence_cn': '吉德·索尔德期望他的儿子继承庄园，但伊塔勒梦想着城市和大学，梦想着山那边的世界。'
    },
    'childhood_07': {
        'id': 'childhood_07',
        'title': 'Emanuel\'s Influence',
        'title_cn': '艾曼纽尔的影响',
        'chapter': 'PART_ONE',
        'category': 'mentor',
        'description': '叔叔Emanuel的开明思想影响了年轻的Itale',
        'description_cn': '叔叔艾曼纽尔的开明思想影响了年轻的伊塔勒',
        'characters': ['emanuel', 'itale', 'perneta'],
        'tags': ['叔侄', '思想', '启蒙'],
        'evidence': 'Emanuel, the younger brother, was a lawyer in Malafrena. He had no children, and treated his nephew and niece with the easy affection of a childless man.',
        'evidence_cn': '艾曼纽尔，弟弟，是Malafrena的律师。他没有孩子，以无子者的轻松感情对待他的侄子和侄女。'
    },
    'childhood_08': {
        'id': 'childhood_08',
        'title': 'The Mountain Paths',
        'title_cn': '山间小路',
        'chapter': 'PART_ONE',
        'category': 'character',
        'description': 'Itale经常独自在山间漫步，思考人生和未来',
        'description_cn': '伊塔勒经常独自在山间漫步，思考人生和未来',
        'characters': ['itale'],
        'tags': ['自然', '思考', '孤独'],
        'evidence': 'He would walk for hours on the mountain paths, going up through the chestnut woods to the high pastures where the air was thin and clear.',
        'evidence_cn': '他会在山间小路上走几个小时，穿过栗树林来到高山牧场，那里的空气稀薄而清新。'
    },
    'childhood_09': {
        'id': 'childhood_09',
        'title': 'Casu\'s Violence',
        'title_cn': '卡苏的暴力',
        'chapter': 'PART_ONE',
        'category': 'family',
        'description': 'Piera的醉汉父亲Casu经常虐待她，促使Eleonora更加保护她',
        'description_cn': '皮耶拉的醉汉父亲卡苏经常虐待她，促使埃莉奥诺拉更加保护她',
        'characters': ['casu', 'piera', 'eleonora'],
        'tags': ['暴力', '保护', '不幸'],
        'evidence': 'Casu had come home drunk, and beaten Piera. Eleonora had taken the child away from him, and after that Piera lived always at the estate.',
        'evidence_cn': '卡苏喝醉了回家，打了皮耶拉。埃莉奥诺拉把孩子从他身边带走，此后皮耶拉一直住在庄园里。'
    },
    'childhood_10': {
        'id': 'childhood_10',
        'title': 'The Harvest Festival',
        'title_cn': '收获节',
        'chapter': 'PART_ONE',
        'category': 'social',
        'description': 'Itale参加村庄的收获节，感受到农民的生活和欢乐',
        'description_cn': '伊塔勒参加村庄的收获节，感受到农民的生活和欢乐',
        'characters': ['itale', 'bron', 'miklos'],
        'tags': ['节日', '村庄', '生活'],
        'evidence': 'The harvest festival brought all the valley people to the estate. There was dancing on the green, and cider, and roasted chestnuts.',
        'evidence_cn': '收获节把山谷里所有的人都带到庄园。草地上有舞蹈，有苹果酒，还有烤栗子。'
    },
    'childhood_11': {
        'id': 'childhood_11',
        'title': 'Political Awakening',
        'title_cn': '政治觉醒',
        'chapter': 'PART_ONE',
        'category': 'politics',
        'description': 'Itale开始阅读政治书籍，对社会不公产生疑问',
        'description_cn': '伊塔勒开始阅读政治书籍，对社会不公产生疑问',
        'characters': ['itale', 'professor_szilagyi', 'emanuel'],
        'tags': ['政治', '觉醒', '思想'],
        'evidence': 'He began to ask why some men owned land and others none, why some were rich and others poor, why the world was so unjust.',
        'evidence_cn': '他开始问为什么有些人拥有土地而其他人没有，为什么有些人富有而其他人贫穷，为什么世界如此不公。'
    },
    'childhood_12': {
        'id': 'childhood_12',
        'title': 'Decision to Leave',
        'title_cn': '离开的决定',
        'chapter': 'PART_ONE',
        'category': 'departure',
        'description': 'Itale决定离开家乡，前往城市追求知识和理想',
        'description_cn': '伊塔勒决定离开家乡，前往城市追求知识和理想',
        'characters': ['itale', 'guide', 'eleonora', 'piera'],
        'tags': ['离别', '追求', '成长'],
        'evidence': 'He told his father that he would not inherit the estate, that he was going to the city to study, to learn, to understand the world.',
        'evidence_cn': '他告诉父亲他不会继承庄园，他要去城市学习，去了解，去理解这个世界。'
    },

    // ============= PART_TWO: 城市生活与革命萌芽 (12个成就) =============
    'city_01': {
        'id': 'city_01',
        'title': 'Arrival in Malafrena',
        'title_cn': '抵达Malafrena',
        'chapter': 'PART_TWO',
        'category': 'arrival',
        'description': 'Itale来到Malafrena城，被城市的繁华和复杂所吸引',
        'description_cn': '伊塔勒来到Malafrena城，被城市的繁华和复杂所吸引',
        'characters': ['itale', 'emanuel', 'perneta'],
        'tags': ['城市', '新环境', '开始'],
        'evidence': 'Malafrena was a city of stone and water, built on seven hills where seven rivers met. Itale had never imagined such a place.',
        'evidence_cn': 'Malafrena是一座石头和水的城市，建在七条河流交汇的七座山丘上。伊塔勒从未想象过这样的地方。'
    },
    'city_02': {
        'id': 'city_02',
        'title': 'Emanuel\'s House',
        'title_cn': '艾曼纽尔的家',
        'chapter': 'PART_TWO',
        'category': 'family',
        'description': 'Itale住在叔叔Emanuel家中，开始适应城市生活',
        'description_cn': '伊塔勒住在叔叔艾曼纽尔家中，开始适应城市生活',
        'characters': ['itale', 'emanuel', 'perneta'],
        'tags': ['家庭', '城市生活', '适应'],
        'evidence': 'Emanuel and Perneta lived in a tall house in the merchant quarter. They welcomed Itale with genuine warmth.',
        'evidence_cn': '艾曼纽尔和佩尔内塔住在商人区的一栋高房子里。他们真诚地欢迎伊塔勒。'
    },
    'city_03': {
        'id': 'city_03',
        'title': 'University Life',
        'title_cn': '大学生活',
        'chapter': 'PART_TWO',
        'category': 'education',
        'description': 'Itale进入大学学习，接触更广阔的知识和思想',
        'description_cn': '伊塔勒进入大学学习，接触更广阔的知识和思想',
        'characters': ['itale', 'professor_szilagyi', 'ivan_kaspe'],
        'tags': ['大学', '知识', '思想'],
        'evidence': 'The university was a world of books and debates, of ideas that soared beyond the mountains of his childhood.',
        'evidence_cn': '大学是一个书籍和辩论的世界，是超越他童年群山的高远思想的世界。'
    },
    'city_04': {
        'id': 'city_04',
        'title': 'Meeting Frenin',
        'title_cn': '遇见弗雷宁',
        'chapter': 'PART_TWO',
        'category': 'character',
        'description': 'Itale在咖啡馆遇见Givan Frenin，两人成为朋友',
        'description_cn': '伊塔勒在咖啡馆遇见吉万·弗雷宁，两人成为朋友',
        'characters': ['itale', 'givan_frenin', 'tomas_brelavay'],
        'tags': ['友谊', '政治', '咖啡馆'],
        'evidence': '"There are about five of us in Amiktiya who are serious about the ideas, right?" Frenin said, his dark eyes bright with enthusiasm.',
        'evidence_cn': '"阿米克蒂亚里大约有五个人对这些理念是认真的，对吧？"弗雷宁说，他黑色的眼睛因热情而闪亮。'
    },
    'city_05': {
        'id': 'city_05',
        'title': 'The Discussion Group',
        'title_cn': '讨论小组',
        'chapter': 'PART_TWO',
        'category': 'politics',
        'description': 'Itale加入Frenin的讨论小组，开始接触革命思想',
        'description_cn': '伊塔勒加入弗雷宁的讨论小组，开始接触革命思想',
        'characters': ['itale', 'givan_frenin', 'tomas_brelavay', 'ivan_kaspe'],
        'tags': ['革命', '讨论', '思想'],
        'evidence': 'They met in a back room of the café, five young men with more ideas than money, more hope than experience.',
        'evidence_cn': '他们在咖啡馆的后房会面，五个年轻人，思想比金钱多，希望比经验多。'
    },
    'city_06': {
        'id': 'city_06',
        'title': 'Stefan Fabbre\'s Speech',
        'title_cn': '斯特凡·法布雷的演讲',
        'chapter': 'PART_TWO',
        'category': 'politics',
        'description': 'Itale第一次听到Stefan Fabbre的演讲，被其魅力征服',
        'description_cn': '伊塔勒第一次听到斯特凡·法布雷的演讲，被其魅力征服',
        'characters': ['itale', 'stefan_fabbre', 'givan_frenin'],
        'tags': ['演讲', '魅力', '革命'],
        'evidence': '"Yes; he\'s what we need; a Danton, a man who can speak for the people." Fabbre\'s voice filled the room, filled their hearts.',
        'evidence_cn': '"是的；他正是我们需要的；像丹东那样的人，能为人民发声。"法布雷的声音充满了房间，充满了他们的心。'
    },
    'city_07': {
        'id': 'city_07',
        'title': 'Writing Pamphlets',
        'title_cn': '撰写小册子',
        'chapter': 'PART_TWO',
        'category': 'action',
        'description': 'Itale开始为革命撰写小册子和传单',
        'description_cn': '伊塔勒开始为革命撰写小册子和传单',
        'characters': ['itale', 'tomas_brelavay', 'lukas_fabbre'],
        'tags': ['写作', '宣传', '革命'],
        'evidence': 'He wrote through the night, his pen flying across the pages. Words of freedom, of justice, of a better world.',
        'evidence_cn': '他通宵写作，笔在纸上飞舞。关于自由、关于正义、关于一个更美好的世界的文字。'
    },
    'city_08': {
        'id': 'city_08',
        'title': 'Secret Meetings',
        'title_cn': '秘密会议',
        'chapter': 'PART_TWO',
        'category': 'action',
        'description': '革命小组在秘密地点举行会议，讨论行动计划',
        'description_cn': '革命小组在秘密地点举行会议，讨论行动计划',
        'characters': ['itale', 'stefan_fabbre', 'givan_frenin', 'tomas_brelavay'],
        'tags': ['秘密', '会议', '计划'],
        'evidence': 'They met in cellars, in attics, in the back rooms of sympathetic merchants. Always moving, always careful.',
        'evidence_cn': '他们在地窖里、阁楼里、同情他们的商人的后房里会面。总是移动，总是小心。'
    },
    'city_09': {
        'id': 'city_09',
        'title': 'First Arrest',
        'title_cn': '第一次被捕',
        'chapter': 'PART_TWO',
        'category': 'action',
        'description': 'Itale因散发传单被警察逮捕，但很快被释放',
        'description_cn': '伊塔勒因散发传单被警察逮捕，但很快被释放',
        'characters': ['itale', 'emanuel', 'constable_janos'],
        'tags': ['逮捕', '警察', '传单'],
        'evidence': 'The constable had been rough but not cruel. "Just doing my job, Herr Sorde," he had muttered.',
        'evidence_cn': '警察很粗暴但不残忍。"只是做我的工作，索尔德先生，"他嘟囔道。'
    },
    'city_10': {
        'id': 'city_10',
        'title': 'Emanuel\'s Warning',
        'title_cn': '艾曼纽尔的警告',
        'chapter': 'PART_TWO',
        'category': 'family',
        'description': 'Emanuel警告Itale政治活动的危险性，但Itale不听',
        'description_cn': '艾曼纽尔警告伊塔勒政治活动的危险性，但伊塔勒不听',
        'characters': ['itale', 'emanuel', 'perneta'],
        'tags': ['警告', '政治', '冲突'],
        'evidence': '"You\'re playing with fire, Itale," Emanuel said. "These are dangerous times." "They\'re dangerous because men like you do nothing!"',
        'evidence_cn': '"你在玩火，伊塔勒，"艾曼纽尔说。"这些是危险的时代。""它们危险是因为像你这样的人什么都不做！"'
    },
    'city_11': {
        'id': 'city_11',
        'title': 'Growing Support',
        'title_cn': '日益增长的支持',
        'chapter': 'PART_TWO',
        'category': 'politics',
        'description': 'Fabbre的演讲吸引了越来越多的支持者',
        'description_cn': '法布雷的演讲吸引了越来越多的支持者',
        'characters': ['stefan_fabbre', 'itale', 'givan_frenin', 'mikhel_dorzu'],
        'tags': ['支持', '群众', '运动'],
        'evidence': 'The crowds grew larger with each meeting. Workers, students, even some merchants came to hear Fabbre speak.',
        'evidence_cn': '每次会议人群都在增长。工人、学生，甚至一些商人都来听法布雷演讲。'
    },
    'city_12': {
        'id': 'city_12',
        'title': 'The Manifesto',
        'title_cn': '宣言',
        'chapter': 'PART_TWO',
        'category': 'action',
        'description': '革命小组起草宣言，准备公开发布',
        'description_cn': '革命小组起草宣言，准备公开发布',
        'characters': ['itale', 'stefan_fabbre', 'tomas_brelavay', 'lukas_fabbre'],
        'tags': ['宣言', '起草', '公开'],
        'evidence': 'They worked on the manifesto all night, arguing over every word. It was to be their declaration to the world.',
        'evidence_cn': '他们通宵起草宣言，对每个词都争论不休。这将是他们对世界的宣言。'
    },

    // ============= PART_THREE: 革命高潮 (12个成就) =============
    'revolution_01': {
        'id': 'revolution_01',
        'title': 'Publication Day',
        'title_cn': '发布日',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': '革命宣言秘密印刷并分发到全城',
        'description_cn': '革命宣言秘密印刷并分发到全城',
        'characters': ['itale', 'lukas_fabbre', 'matej_kosut', 'stefan_fabbre'],
        'tags': ['印刷', '分发', '宣言'],
        'evidence': 'By dawn, the manifesto was everywhere—on walls, in doorways, even in the cathedral.',
        'evidence_cn': '到黎明时，宣言到处都是——在墙上、门口，甚至在大教堂里。'
    },
    'revolution_02': {
        'id': 'revolution_02',
        'title': 'Government Reaction',
        'title_cn': '政府反应',
        'chapter': 'PART_THREE',
        'category': 'politics',
        'description': 'Count Vespini下令镇压革命活动，加强警戒',
        'description_cn': '维斯皮尼伯爵下令镇压革命活动，加强警戒',
        'characters': ['count_vespini', 'colonel_tulkats', 'major_kovats'],
        'tags': ['镇压', '政府', '警戒'],
        'evidence': 'Count Vespini summoned Colonel Tulkats. "I want these agitators found and arrested. All of them."',
        'evidence_cn': '维斯皮尼伯爵召见图尔卡茨上校。"我要找到这些煽动者并逮捕他们。所有人。"'
    },
    'revolution_03': {
        'id': 'revolution_03',
        'title': 'Mass Rally',
        'title_cn': '群众集会',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': 'Fabbre组织大规模群众集会，抗议政府政策',
        'description_cn': '法布雷组织大规模群众集会，抗议政府政策',
        'characters': ['stefan_fabbre', 'itale', 'givan_frenin', 'mikhel_dorzu'],
        'tags': ['集会', '抗议', '群众'],
        'evidence': 'Thousands gathered in the main square. Fabbre stood on a cart, his voice carrying to every corner.',
        'evidence_cn': '数千人聚集在主广场。法布雷站在马车上，他的声音传到每个角落。'
    },
    'revolution_04': {
        'id': 'revolution_04',
        'title': 'Military Intervention',
        'title_cn': '军事干预',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': '军队驱散集会，与民众发生冲突',
        'description_cn': '军队驱散集会，与民众发生冲突',
        'characters': ['colonel_tulkats', 'major_kovats', 'stefan_fabbre', 'itale'],
        'tags': ['军队', '冲突', '暴力'],
        'evidence': 'The soldiers came with fixed bayonets. The crowd scattered, but not before blood had been shed on the stones.',
        'evidence_cn': '士兵们端着刺刀来了。人群四散，但在石头上的血流出之前还没有。'
    },
    'revolution_05': {
        'id': 'revolution_05',
        'title': 'Underground Network',
        'title_cn': '地下网络',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': '革命者建立地下网络，继续秘密活动',
        'description_cn': '革命者建立地下网络，继续秘密活动',
        'characters': ['itale', 'tomas_brelavay', 'givan_frenin', 'andrej_horvath'],
        'tags': ['地下', '秘密', '网络'],
        'evidence': 'They organized in cells, each member knowing only a few others. Messages passed by hand, by night.',
        'evidence_cn': '他们以小组为单位组织，每个成员只知道少数其他人。信息在夜间亲手传递。'
    },
    'revolution_06': {
        'id': 'revolution_06',
        'title': 'Karoly\'s Support',
        'title_cn': '卡罗伊的支持',
        'chapter': 'PART_THREE',
        'category': 'politics',
        'description': '商人Karoly为革命提供资金和庇护',
        'description_cn': '商人卡罗伊为革命提供资金和庇护',
        'characters': ['merchant_karoly', 'mrs_karoly', 'itale', 'stefan_fabbre'],
        'tags': ['支持', '资金', '庇护'],
        'evidence': 'Merchant Karoly opened his house to the revolutionaries. "I believe in what you\'re doing," he said.',
        'evidence_cn': '商人卡罗伊向革命者开放了他的房子。"我相信你们正在做的事情，"他说。'
    },
    'revolution_07': {
        'id': 'revolution_07',
        'title': 'Franz Bauer\'s Arrival',
        'title_cn': '弗朗茨·鲍尔的到来',
        'chapter': 'PART_THREE',
        'category': 'character',
        'description': '奥地利革命者Franz Bauer来到Malafrena，带来外部经验',
        'description_cn': '奥地利革命者弗朗茨·鲍尔来到Malafrena，带来外部经验',
        'characters': ['franz_bauer', 'stefan_fabbre', 'itale'],
        'tags': ['革命', '经验', '国际'],
        'evidence': 'Bauer had fought in Vienna. His scarred face and calm voice spoke of experience beyond their years.',
        'evidence_cn': '鲍尔曾在维也纳战斗。他疤痕的脸和冷静的声音诉说着超越他们年龄的经验。'
    },
    'revolution_08': {
        'id': 'revolution_08',
        'title': 'The Plan',
        'title_cn': '计划',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': '革命者制定武装起义的详细计划',
        'description_cn': '革命者制定武装起义的详细计划',
        'characters': ['stefan_fabbre', 'itale', 'franz_bauer', 'givan_frenin'],
        'tags': ['计划', '起义', '武装'],
        'evidence': 'They planned every detail—the timing, the signals, the targets. Victory or death, there would be no turning back.',
        'evidence_cn': '他们计划了每个细节——时间、信号、目标。胜利或死亡，不会有回头路。'
    },
    'revolution_09': {
        'id': 'revolution_09',
        'title': 'Piera\'s Letter',
        'title_cn': '皮耶拉的信',
        'chapter': 'PART_THREE',
        'category': 'romance',
        'description': 'Piera写信给Itale，表达对他的思念和担忧',
        'description_cn': '皮耶拉写信给伊塔勒，表达对他的思念和担忧',
        'characters': ['piera', 'itale', 'eleonora'],
        'tags': ['思念', '担忧', '爱情'],
        'evidence': 'Dearest Itale, I pray you are safe. The city is dangerous, they say. Come home when you can.',
        'evidence_cn': '最亲爱的伊塔勒，我祈祷你平安。他们说城市很危险。可以的时候就回家吧。'
    },
    'revolution_10': {
        'id': 'revolution_10',
        'title': 'The Uprising Begins',
        'title_cn': '起义开始',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': '革命者按计划发动武装起义',
        'description_cn': '革命者按计划发动武装起义',
        'characters': ['stefan_fabbre', 'itale', 'givan_frenin', 'tomas_brelavay'],
        'tags': ['起义', '武装', '行动'],
        'evidence': 'At midnight the signal fires were lit. From every quarter of the city, the revolutionaries rose.',
        'evidence_cn': '午夜时分，信号火被点燃。从城市的每个区域，革命者起义了。'
    },
    'revolution_11': {
        'id': 'revolution_11',
        'title': 'Street Fighting',
        'title_cn': '巷战',
        'chapter': 'PART_THREE',
        'category': 'action',
        'description': '起义者与军队在街头展开激烈战斗',
        'description_cn': '起义者与军队在街头展开激烈战斗',
        'characters': ['itale', 'stefan_fabbre', 'major_kovats', 'captain_szel'],
        'tags': ['战斗', '街头', '暴力'],
        'evidence': 'The narrow streets echoed with gunfire. Barricades went up at every corner.',
        'evidence_cn': '狭窄的街道上回荡着枪声。每个街角都竖起了路障。'
    },
    'revolution_12': {
        'id': 'revolution_12',
        'title': 'The Betrayal',
        'title_cn': '背叛',
        'chapter': 'PART_THREE',
        'category': 'mystery',
        'description': '起义计划被泄露，革命者遭到伏击',
        'description_cn': '起义计划被泄露，革命者遭到伏击',
        'characters': ['stefan_fabbre', 'itale', 'jan_lukas', 'count_vespini'],
        'tags': ['背叛', '伏击', '失败'],
        'evidence': 'They had been betrayed. The soldiers were waiting, the trap sprung.',
        'evidence_cn': '他们被背叛了。士兵们在等待，陷阱已经设好。'
    },

    // ============= PART_FOUR: 审判与囚禁 (12个成就) =============
    'prison_01': {
        'id': 'prison_01',
        'title': 'Mass Arrests',
        'title_cn': '大规模逮捕',
        'chapter': 'PART_FOUR',
        'category': 'action',
        'description': '政府大规模逮捕革命者，Itale和Fabbre被捕',
        'description_cn': '政府大规模逮捕革命者，伊塔勒和法布雷被捕',
        'characters': ['itale', 'stefan_fabbre', 'givan_frenin', 'sergeant_bartok'],
        'tags': ['逮捕', '监狱', '镇压'],
        'evidence': 'The arrests began at dawn. House by house, the soldiers came.',
        'evidence_cn': '逮捕在黎明开始。挨家挨户，士兵们来了。'
    },
    'prison_02': {
        'id': 'prison_02',
        'title': 'The Trial',
        'title_cn': '审判',
        'chapter': 'PART_FOUR',
        'category': 'politics',
        'description': '革命者接受审判，被指控叛国罪',
        'description_cn': '革命者接受审判，被指控叛国罪',
        'characters': ['itale', 'stefan_fabbre', 'judge_hettar', 'prosecutor_kulon'],
        'tags': ['审判', '法庭', '叛国'],
        'evidence': 'The courtroom was packed. Judge Hettar read the charges: treason against the Empire.',
        'evidence_cn': '法庭挤满了人。赫塔尔法官宣读指控：叛国罪，对抗帝国。'
    },
    'prison_03': {
        'id': 'prison_03',
        'title': 'Fabbre\'s Defense',
        'title_cn': '法布雷的辩护',
        'chapter': 'PART_FOUR',
        'category': 'politics',
        'description': 'Fabbre在法庭上发表了慷慨激昂的辩护演讲',
        'description_cn': '法布雷在法庭上发表了慷慨激昂的辩护演讲',
        'characters': ['stefan_fabbre', 'judge_hettar', 'itale'],
        'tags': ['辩护', '演讲', '正义'],
        'evidence': 'Fabbre spoke for three hours, not in his own defense, but for the people, for justice, for freedom.',
        'evidence_cn': '法布雷讲了三个小时，不是为自己辩护，而是为人民、为正义、为自由。'
    },
    'prison_04': {
        'id': 'prison_04',
        'title': 'The Sentence',
        'title_cn': '判决',
        'chapter': 'PART_FOUR',
        'category': 'action',
        'description': '法庭判处主要革命者死刑，Itale被判终身监禁',
        'description_cn': '法庭判处主要革命者死刑，伊塔勒被判终身监禁',
        'characters': ['stefan_fabbre', 'itale', 'judge_hettar', 'count_vespini'],
        'tags': ['死刑', '判决', '监狱'],
        'evidence': 'Stefan Fabbre: death. Itale Sorde: life imprisonment. The words echoed in the silent courtroom.',
        'evidence_cn': '斯特凡·法布雷：死刑。伊塔勒·索尔德：终身监禁。这些话在寂静的法庭中回响。'
    },
    'prison_05': {
        'id': 'prison_05',
        'title': 'Prison Life',
        'title_cn': '监狱生活',
        'chapter': 'PART_FOUR',
        'category': 'character',
        'description': 'Itale在监狱中坚持信念，继续思考和写作',
        'description_cn': '伊塔勒在监狱中坚持信念，继续思考和写作',
        'characters': ['itale', 'prison_warden_fejos', 'jailer_kis'],
        'tags': ['监狱', '坚持', '思考'],
        'evidence': 'The cell was small and dark, but his mind remained free. He wrote on scraps of paper, hiding them from the guards.',
        'evidence_cn': '牢房又小又黑，但他的思想仍然是自由的。他在碎纸片上写字，不让警卫发现。'
    },
    'prison_06': {
        'id': 'prison_06',
        'title': 'Fabbre\'s Execution',
        'title_cn': '法布雷的处决',
        'chapter': 'PART_FOUR',
        'category': 'action',
        'description': 'Stefan Fabbre被公开处决，成为革命烈士',
        'description_cn': '斯特凡·法布雷被公开处决，成为革命烈士',
        'characters': ['stefan_fabbre', 'executioner', 'count_vespini', 'itale'],
        'tags': ['处决', '烈士', '牺牲'],
        'evidence': 'They marched him to the square. He walked proudly, his head high. The crowd was silent.',
        'evidence_cn': '他们把他押到广场。他骄傲地走着，高昂着头。人群沉默着。'
    },
    'prison_07': {
        'id': 'prison_07',
        'title': 'Prison Letters',
        'title_cn': '狱中书信',
        'chapter': 'PART_FOUR',
        'category': 'romance',
        'description': 'Itale在狱中收到Piera和家人的来信',
        'description_cn': '伊塔勒在狱中收到皮耶拉和家人的来信',
        'characters': ['itale', 'piera', 'eleonora', 'laura'],
        'tags': ['书信', '思念', '家人'],
        'evidence': 'The letters came rarely, smuggled in by sympathetic guards. Piera\'s handwriting, his mother\'s gentle words.',
        'evidence_cn': '信件很少来，由同情的警卫偷运进来。皮耶拉的笔迹，母亲温柔的话语。'
    },
    'prison_08': {
        'id': 'prison_08',
        'title': 'The Betrayer Revealed',
        'title_cn': '背叛者揭露',
        'chapter': 'PART_FOUR',
        'category': 'mystery',
        'description': 'Itale发现是Jan Lukas背叛了革命组织',
        'description_cn': '伊塔勒发现是扬·卢卡斯背叛了革命组织',
        'characters': ['itale', 'jan_lukas', 'givan_frenin'],
        'tags': ['背叛', '揭露', '真相'],
        'evidence': 'Lukas had been afraid, had traded their lives for his freedom. The knowledge burned like acid.',
        'evidence_cn': '卢卡斯害怕了，用他们的生命换取他的自由。这知识像酸一样灼烧着。'
    },
    'prison_09': {
        'id': 'prison_09',
        'title': 'Frenin\'s Escape',
        'title_cn': '弗雷宁的逃脱',
        'chapter': 'PART_FOUR',
        'category': 'action',
        'description': 'Frenin成功逃脱，继续地下活动',
        'description_cn': '弗雷宁成功逃脱，继续地下活动',
        'characters': ['givan_frenin', 'itale', 'tomas_brelavay'],
        'tags': ['逃脱', '地下', '继续'],
        'evidence': 'Frenin was gone, vanished from the prison. They said he had help from outside, from friends still free.',
        'evidence_cn': '弗雷宁走了，从监狱里消失了。他们说他得到了外面的帮助，来自仍然自由的朋友。'
    },
    'prison_10': {
        'id': 'prison_10',
        'title': 'Dr. Koves\' Visit',
        'title_cn': '科韦什医生的探访',
        'chapter': 'PART_FOUR',
        'category': 'character',
        'description': 'Dr. Koves前来探望Itale，带来外界消息',
        'description_cn': '科韦什医生前来探望伊塔勒，带来外界消息',
        'characters': ['dr_janos_koves', 'itale', 'emanuel'],
        'tags': ['探访', '消息', '希望'],
        'evidence': '"Your family is well," the doctor said. "Your uncle sends his love. Hold fast, Itale."',
        'evidence_cn': '"你的家人都很好，"医生说。"你的叔叔送上他的爱。坚持住，伊塔勒。"'
    },
    'prison_11': {
        'id': 'prison_11',
        'title': 'Prison Rebellion',
        'title_cn': '监狱叛乱',
        'chapter': 'PART_FOUR',
        'category': 'action',
        'description': 'Itale领导囚犯进行绝食抗议',
        'description_cn': '伊塔勒领导囚犯进行绝食抗议',
        'characters': ['itale', 'prison_warden_fejos', 'mikhel_dorzu'],
        'tags': ['抗议', '绝食', '领导'],
        'evidence': '"We demand better conditions!" Itale shouted. "We are men, not animals!"',
        'evidence_cn': '"我们要求更好的条件！"伊塔勒喊道。"我们是人，不是动物！"'
    },
    'prison_12': {
        'id': 'prison_12',
        'title': 'The Long Years',
        'title_cn': '漫长岁月',
        'chapter': 'PART_FOUR',
        'category': 'character',
        'description': 'Itale在监狱中度过漫长的岁月，但信念从未动摇',
        'description_cn': '伊塔勒在监狱中度过漫长的岁月，但信念从未动摇',
        'characters': ['itale', 'piera', 'eleonora'],
        'tags': ['岁月', '信念', '坚持'],
        'evidence': 'Years passed. The world outside changed, but the prison walls remained. Yet in his heart, the fire of revolution never died.',
        'evidence_cn': '岁月流逝。外面的世界变了，但监狱的墙壁依然如故。然而在他心中，革命的火焰从未熄灭。'
    },

    // ============= PART_FIVE: 逃亡与流亡 (12个成就) =============
    'escape_01': {
        'id': 'escape_01',
        'title': 'Prison Break',
        'title_cn': '越狱',
        'chapter': 'PART_FIVE',
        'category': 'action',
        'description': 'Itale在朋友的帮助下成功越狱',
        'description_cn': '伊塔勒在朋友的帮助下成功越狱',
        'characters': ['itale', 'givan_frenin', 'tomas_brelavay'],
        'tags': ['越狱', '帮助', '自由'],
        'evidence': 'The guard turned away at the crucial moment. The key fit perfectly. And then—freedom.',
        'evidence_cn': '警卫在关键时刻转过身去。钥匙完美契合。然后——自由。'
    },
    'escape_02': {
        'id': 'escape_02',
        'title': 'Flight through the Mountains',
        'title_cn': '穿越山脉',
        'chapter': 'PART_FIVE',
        'category': 'action',
        'description': 'Itale穿越山脉逃往邻国',
        'description_cn': '伊塔勒穿越山脉逃往邻国',
        'characters': ['itale', 'ferenc'],
        'tags': ['逃亡', '山脉', '边境'],
        'evidence': 'He walked by night, hiding by day. The mountains were cold, the paths treacherous, but each step took him further from the prison.',
        'evidence_cn': '他夜间行走，白天躲藏。山脉寒冷，道路危险，但每一步都让他离监狱更远。'
    },
    'escape_03': {
        'id': 'escape_03',
        'title': 'Border Crossing',
        'title_cn': '穿越边境',
        'chapter': 'PART_FIVE',
        'category': 'action',
        'description': 'Itale在边境被海关官员盘问，但成功通过',
        'description_cn': '伊塔勒在边境被海关官员盘问，但成功通过',
        'characters': ['itale', 'customs_officer_kral'],
        'tags': ['边境', '盘问', '逃脱'],
        'evidence': '"Your papers, sir?" The customs officer looked suspicious. Itale\'s heart pounded, but his face remained calm.',
        'evidence_cn': '"您的证件，先生？"海关官员看起来很怀疑。伊塔勒的心砰砰直跳，但他的脸保持平静。'
    },
    'escape_04': {
        'id': 'escape_04',
        'title': 'Exile Community',
        'title_cn': '流亡者社区',
        'chapter': 'PART_FIVE',
        'category': 'character',
        'description': 'Itale加入流亡者社区，继续革命活动',
        'description_cn': '伊塔勒加入流亡者社区，继续革命活动',
        'characters': ['itale', 'franz_bauer', 'givan_frenin'],
        'tags': ['流亡', '社区', '继续'],
        'evidence': 'In the foreign city, he found others like himself—exiles, dreamers, those who had fought and lost but not surrendered.',
        'evidence_cn': '在外国城市，他找到了像他一样的人——流亡者、梦想家、那些战斗过、失败过但没有投降的人。'
    },
    'escape_05': {
        'id': 'escape_05',
        'title': 'Letters Home',
        'title_cn': '家书',
        'chapter': 'PART_FIVE',
        'category': 'romance',
        'description': 'Itale通过秘密渠道与家人和Piera通信',
        'description_cn': '伊塔勒通过秘密渠道与家人和皮耶拉通信',
        'characters': ['itale', 'piera', 'eleonora', 'laura'],
        'tags': ['书信', '家人', '联系'],
        'evidence': 'The letters took months to arrive, passed from hand to hand across borders. Each word was precious.',
        'evidence_cn': '信件需要几个月才能到达，在边境间人手相传。每个字都是珍贵的。'
    },
    'escape_06': {
        'id': 'escape_06',
        'title': 'Revolutionary Activities',
        'title_cn': '革命活动',
        'chapter': 'PART_FIVE',
        'category': 'politics',
        'description': 'Itale在流亡中继续参与革命活动',
        'description_cn': '伊塔勒在流亡中继续参与革命活动',
        'characters': ['itale', 'franz_bauer', 'givan_frenin', 'josef_kollár'],
        'tags': ['革命', '流亡', '活动'],
        'evidence': 'They published pamphlets, organized meetings, kept the flame of revolution alive in exile.',
        'evidence_cn': '他们出版小册子，组织会议，在流亡中保持革命的火焰不熄。'
    },
    'escape_07': {
        'id': 'escape_07',
        'title': 'News from Home',
        'title_cn': '家乡消息',
        'chapter': 'PART_FIVE',
        'category': 'family',
        'description': 'Itale收到家乡的消息，得知父亲病重',
        'description_cn': '伊塔勒收到家乡的消息，得知父亲病重',
        'characters': ['itale', 'emanuel', 'guide', 'eleonora'],
        'tags': ['消息', '父亲', '疾病'],
        'evidence': 'Your father is ill, the letter said. Not expected to recover. Come home if you can.',
        'evidence_cn': '"你父亲病了，"信中说。"预计无法康复。如果可以就回家吧。"'
    },
    'escape_08': {
        'id': 'escape_08',
        'title': 'The Dilemma',
        'title_cn': '两难选择',
        'chapter': 'PART_FIVE',
        'category': 'character',
        'description': 'Itale面临选择：留在安全的流亡地，还是冒险回家',
        'description_cn': '伊塔勒面临选择：留在安全的流亡地，还是冒险回家',
        'characters': ['itale', 'givan_frenin', 'franz_bauer'],
        'tags': ['选择', '两难', '决定'],
        'evidence': '"If you go back, they\'ll arrest you," Frenin warned. "If I don\'t, I\'ll never see my father again," Itale replied.',
        'evidence_cn': '"如果你回去，他们会逮捕你，"弗雷宁警告说。"如果我不回去，我再也见不到我父亲了，"伊塔勒回答。'
    },
    'escape_09': {
        'id': 'escape_09',
        'title': 'Journey Home',
        'title_cn': '回家之路',
        'chapter': 'PART_FIVE',
        'category': 'action',
        'description': 'Itale决定冒险回家，穿越危险的边境',
        'description_cn': '伊塔勒决定冒险回家，穿越危险的边境',
        'characters': ['itale', 'tomas_brelavay'],
        'tags': ['回家', '冒险', '边境'],
        'evidence': 'He traveled by night, through forests and over mountains, each step taking him closer to home.',
        'evidence_cn': '他夜间旅行，穿过森林，越过山脉，每一步都让他更接近家。'
    },
    'escape_10': {
        'id': 'escape_10',
        'title': 'Close Encounter',
        'title_cn': '近距离接触',
        'chapter': 'PART_FIVE',
        'category': 'action',
        'description': 'Itale在途中差点被巡逻队发现',
        'description_cn': '伊塔勒在途中差点被巡逻队发现',
        'characters': ['itale', 'lieutenant_horn', 'constable_janos'],
        'tags': ['危险', '巡逻', '逃脱'],
        'evidence': 'He pressed himself against the wall as the patrol passed. A voice called out, but they moved on.',
        'evidence_cn': '他紧贴着墙，巡逻队经过时。一个声音喊出来，但他们继续前进了。'
    },
    'escape_11': {
        'id': 'escape_11',
        'title': 'Safe House',
        'title_cn': '安全屋',
        'chapter': 'PART_FIVE',
        'category': 'action',
        'description': 'Itale在同情者的帮助下找到临时避难所',
        'description_cn': '伊塔勒在同情者的帮助下找到临时避难所',
        'characters': ['itale', 'abbe_garamond', 'dr_janos_koves'],
        'tags': ['避难', '帮助', '同情'],
        'evidence': 'The priest gave him shelter. "God protects the innocent," he said, though both knew the world did not.',
        'evidence_cn': '神父给了他庇护。"上帝保护无辜者，"他说，尽管两人都知道世界不是这样。'
    },
    'escape_12': {
        'id': 'escape_12',
        'title': 'The Valley Again',
        'title_cn': '重见山谷',
        'chapter': 'PART_FIVE',
        'category': 'arrival',
        'description': 'Itale终于看到家乡的山谷，但知道不能停留',
        'description_cn': '伊塔勒终于看到家乡的山谷，但知道不能停留',
        'characters': ['itale', 'ferenc'],
        'tags': ['山谷', '家乡', '短暂'],
        'evidence': 'The valley lay before him, green and beautiful in the morning light. Home—so close, yet forever out of reach.',
        'evidence_cn': '山谷在他面前，在晨光中翠绿而美丽。家——如此接近，却永远遥不可及。'
    },

    // ============= PART_SIX: 归来与和解 (12个成就) =============
    'return_01': {
        'id': 'return_01',
        'title': 'Father\'s Deathbed',
        'title_cn': '父亲的临终',
        'chapter': 'PART_SIX',
        'category': 'family',
        'description': 'Itale偷偷回家，在父亲临终前与他相见',
        'description_cn': '伊塔勒偷偷回家，在父亲临终前与他相见',
        'characters': ['itale', 'guide', 'eleonora', 'emanuel'],
        'tags': ['临终', '和解', '父亲'],
        'evidence': '"I was wrong, Father." "No, my son. You were right—about everything."',
        'evidence_cn': '"我错了，父亲。""不，我的儿子。你是对的——关于一切。"'
    },
    'return_02': {
        'id': 'return_02',
        'title': 'Family Reunion',
        'title_cn': '家庭团聚',
        'chapter': 'PART_SIX',
        'category': 'family',
        'description': 'Itale与家人短暂团聚，但知道必须离开',
        'description_cn': '伊塔勒与家人短暂团聚，但知道必须离开',
        'characters': ['itale', 'eleonora', 'laura', 'piera'],
        'tags': ['团聚', '短暂', '离别'],
        'evidence': 'His mother held him close. "My boy, my boy." Piera wept silently in the corner.',
        'evidence_cn': '他的母亲紧紧地抱着他。"我的孩子，我的孩子。"皮耶拉在角落里默默地哭泣。'
    },
    'return_03': {
        'id': 'return_03',
        'title': 'Piera\'s Confession',
        'title_cn': '皮耶拉的告白',
        'chapter': 'PART_SIX',
        'category': 'romance',
        'description': 'Piera向Itale表白，愿意等他回来',
        'title_cn': '皮耶拉的告白',
        'characters': ['piera', 'itale', 'eleonora'],
        'tags': ['告白', '等待', '爱情'],
        'evidence': '"I\'ll wait for you," she whispered. "Forever, if I must."',
        'evidence_cn': '"我会等你，"她低声说。"如果需要，永远等下去。"'
    },
    'return_04': {
        'id': 'return_04',
        'title': 'The Funeral',
        'title_cn': '葬礼',
        'chapter': 'PART_SIX',
        'category': 'family',
        'description': 'Itale秘密参加父亲的葬礼',
        'description_cn': '伊塔勒秘密参加父亲的葬礼',
        'characters': ['itale', 'guide', 'eleonora', 'laura', 'emanuel'],
        'tags': ['葬礼', '秘密', '告别'],
        'evidence': 'He watched from a distance as they lowered the coffin. The father he had loved and fought with, now at peace.',
        'evidence_cn': '他从远处看着他们把棺材放下。他曾爱过、与之争斗过的父亲，现在安息了。'
    },
    'return_05': {
        'id': 'return_05',
        'title': 'Inheritance',
        'title_cn': '继承',
        'chapter': 'PART_SIX',
        'category': 'family',
        'description': 'Itale继承庄园，但将其委托给母亲和叔叔管理',
        'description_cn': '伊塔勒继承庄园，但将其委托给母亲和叔叔管理',
        'characters': ['itale', 'eleonora', 'emanuel', 'laura'],
        'tags': ['继承', '委托', '责任'],
        'evidence': '"The estate is yours now," Emanuel said. "It will wait for you."',
        'evidence_cn': '"庄园现在是你的了，"艾曼纽尔说。"它会等你。"'
    },
    'return_06': {
        'id': 'return_06',
        'title': 'Laura\'s Growth',
        'title_cn': '劳拉的成长',
        'chapter': 'PART_SIX',
        'category': 'character',
        'description': 'Itale发现妹妹Laura已经成长为独立的女性',
        'description_cn': '伊塔勒发现妹妹劳拉已经成长为独立的女性',
        'characters': ['laura', 'itale', 'eleonora'],
        'tags': ['成长', '独立', '变化'],
        'evidence': 'Laura was no longer the child he remembered. She spoke of books, of ideas, of a life beyond the valley.',
        'evidence_cn': '劳拉不再是他记忆中的孩子了。她谈论书籍、思想、山谷之外的生活。'
    },
    'return_07': {
        'id': 'return_07',
        'title': 'The Old Servants',
        'title_cn': '老仆人',
        'chapter': 'PART_SIX',
        'category': 'character',
        'description': 'Itale与老仆人Bron和Kathi重逢',
        'description_cn': '伊塔勒与老仆人布隆和卡蒂重逢',
        'characters': ['itale', 'bron', 'kathi', 'miklos'],
        'tags': ['重逢', '忠诚', '仆人'],
        'evidence': 'Bron wept openly. "Master Itale, we thought you were dead." "Not dead, Bron. Just... delayed."',
        'evidence_cn': '布隆公开哭泣。"伊塔勒少爷，我们以为你死了。""没有死，布隆。只是... 耽搁了。"'
    },
    'return_08': {
        'id': 'return_08',
        'title': 'Village Changes',
        'title_cn': '村庄变化',
        'chapter': 'PART_SIX',
        'category': 'character',
        'description': 'Itale发现村庄也发生了许多变化',
        'description_cn': '伊塔勒发现村庄也发生了许多变化',
        'characters': ['itale', 'village_priest', 'schoolmaster_harmat'],
        'tags': ['变化', '村庄', '时间'],
        'evidence': 'The village was the same, yet different. New houses, new faces, but the old spirit remained.',
        'evidence_cn': '村庄还是一样，但又不同。新房子，新面孔，但旧的精神依然存在。'
    },
    'return_09': {
        'id': 'return_09',
        'title': 'Night in the Library',
        'title_cn': '图书馆之夜',
        'chapter': 'PART_SIX',
        'category': 'character',
        'description': 'Itale重访图书馆，回顾自己的人生旅程',
        'description_cn': '伊塔勒重访图书馆，回顾自己的人生旅程',
        'characters': ['itale', 'laura', 'eleonora'],
        'tags': ['图书馆', '回忆', '旅程'],
        'evidence': 'The books were still there, the same titles that had opened his mind to new ideas. How young he had been.',
        'evidence_cn': '书还在那里，那些曾让他的思想接触新观念的相同的书名。他曾经是那么的年轻。'
    },
    'return_10': {
        'id': 'return_10',
        'title': 'The Decision',
        'title_cn': '决定',
        'chapter': 'PART_SIX',
        'category': 'character',
        'description': 'Itale决定再次离开，继续革命事业',
        'description_cn': '伊塔勒决定再次离开，继续革命事业',
        'characters': ['itale', 'eleonora', 'emanuel', 'piera'],
        'tags': ['决定', '离开', '事业'],
        'evidence': '"I must go back," he said. "The work isn\'t finished." His mother nodded, understanding in her eyes.',
        'evidence_cn': '"我必须回去，"他说。"工作还没有完成。"他的母亲点点头，眼中含着理解。'
    },
    'return_11': {
        'id': 'return_11',
        'title': 'Farewell',
        'title_cn': '告别',
        'chapter': 'PART_SIX',
        'category': 'departure',
        'description': 'Itale与所有人告别，承诺会回来',
        'description_cn': '伊塔勒与所有人告别，承诺会回来',
        'characters': ['itale', 'piera', 'eleonora', 'laura', 'emanuel'],
        'tags': ['告别', '承诺', '离开'],
        'evidence': '"I\'ll come back," he promised. "When the work is done, when the world is different."',
        'evidence_cn': '"我会回来的，"他承诺。"当工作完成时，当世界不同时。"'
    },
    'return_12': {
        'id': 'return_12',
        'title': 'The Road Ahead',
        'title_cn': '前路',
        'chapter': 'PART_SIX',
        'category': 'departure',
        'description': 'Itale踏上新的旅程，面对未知的未来',
        'description_cn': '伊塔勒踏上新的旅程，面对未知的未来',
        'characters': ['itale', 'givan_frenin'],
        'tags': ['旅程', '未来', '希望'],
        'evidence': 'The road stretched before him, leading to cities, to battles, to an uncertain future. But he walked it willingly.',
        'evidence_cn': '道路在他面前延伸，通向城市、战斗、不确定的未来。但他愿意走这条路。'
    },

    // ============= PART_SEVEN: 结局 (12个成就) =============
    'ending_01': {
        'id': 'ending_01',
        'title': 'Years Later',
        'title_cn': '多年以后',
        'chapter': 'PART_SEVEN',
        'category': 'character',
        'description': '多年后，Itale作为成熟的革命者回顾自己的人生',
        'description_cn': '多年后，伊塔勒作为成熟的革命者回顾自己的人生',
        'characters': ['itale', 'givan_frenin', 'tomas_brelavay'],
        'tags': ['回顾', '成熟', '人生'],
        'evidence': 'His hair was grey now, his face lined with experience. But the fire in his eyes had not dimmed.',
        'evidence_cn': '他的头发现在灰白了，他的脸因经验而布满皱纹。但他眼中的火焰没有减弱。'
    },
    'ending_02': {
        'id': 'ending_02',
        'title': 'Revolutionary Success',
        'title_cn': '革命成功',
        'chapter': 'PART_SEVEN',
        'category': 'politics',
        'description': '革命运动在各地取得成功',
        'description_cn': '革命运动在各地取得成功',
        'characters': ['itale', 'givan_frenin', 'franz_bauer'],
        'tags': ['成功', '革命', '胜利'],
        'evidence': 'The old order was falling. In city after city, the people were rising, taking back their rights.',
        'evidence_cn': '旧秩序正在崩溃。在一个又一个城市，人民正在崛起，夺回他们的权利。'
    },
    'ending_03': {
        'id': 'ending_03',
        'title': 'Return to the Valley',
        'title_cn': '回到山谷',
        'chapter': 'PART_SEVEN',
        'category': 'arrival',
        'description': 'Itale作为胜利者回到Malafrena山谷',
        'description_cn': '伊塔勒作为胜利者回到Malafrena山谷',
        'characters': ['itale', 'eleonora', 'laura', 'bron'],
        'tags': ['归来', '胜利', '山谷'],
        'evidence': 'The valley welcomed him home. The mountains stood as they always had, eternal witnesses.',
        'evidence_cn': '山谷欢迎他回家。群山如它们一直以来的那样矗立，永恒的见证者。'
    },
    'ending_04': {
        'id': 'ending_04',
        'title': 'Laura\'s Marriage',
        'title_cn': '劳拉的婚礼',
        'chapter': 'PART_SEVEN',
        'category': 'family',
        'description': 'Laura与一位进步学者结婚',
        'description_cn': '劳拉与一位进步学者结婚',
        'characters': ['laura', 'itale', 'eleonora'],
        'tags': ['婚礼', '幸福', '家庭'],
        'evidence': 'Laura had married well, to a man who shared her love of learning. They would build a new world together.',
        'evidence_cn': '劳拉嫁得很好，嫁给了一个分享她对学习的热爱的人。他们将一起建设一个新世界。'
    },
    'ending_05': {
        'id': 'ending_05',
        'title': 'Piera\'s Wait',
        'title_cn': '皮耶拉的等待',
        'chapter': 'PART_SEVEN',
        'category': 'romance',
        'description': 'Piera信守承诺，一直等待着Itale',
        'description_cn': '皮耶拉信守承诺，一直等待着伊塔勒',
        'characters': ['piera', 'itale', 'eleonora'],
        'tags': ['等待', '承诺', '爱情'],
        'evidence': 'She had waited, as she promised. Her hair was touched with silver, but her eyes were the same.',
        'evidence_cn': '她信守承诺，一直等着。她的头发已现银丝，但她的眼睛还是一样。'
    },
    'ending_06': {
        'id': 'ending_06',
        'title': 'The Wedding',
        'title_cn': '婚礼',
        'chapter': 'PART_SEVEN',
        'category': 'romance',
        'description': 'Itale和Piera终于举行婚礼',
        'description_cn': '伊塔勒和皮耶拉终于举行婚礼',
        'characters': ['itale', 'piera', 'eleonora', 'laura', 'emanuel'],
        'tags': ['婚礼', '爱情', '圆满'],
        'evidence': 'They were married in the little church where generations of Sordes had been wed. This time, no one objected.',
        'evidence_cn': '他们在几代索尔德家族成员结婚的小教堂里结婚了。这次，没有人反对。'
    },
    'ending_07': {
        'id': 'ending_07',
        'title': 'The Estate Restored',
        'title_cn': '庄园复兴',
        'chapter': 'PART_SEVEN',
        'category': 'family',
        'description': 'Itale重新管理庄园，带来新的改革',
        'description_cn': '伊塔勒重新管理庄园，带来新的改革',
        'characters': ['itale', 'piera', 'bron', 'kathi', 'miklos'],
        'tags': ['庄园', '改革', '管理'],
        'evidence': 'The estate flourished under his care. New methods, new ideas, but always with respect for the land and the people.',
        'evidence_cn': '庄园在他的照料下繁荣起来。新方法，新思想，但总是尊重土地和人民。'
    },
    'ending_08': {
        'id': 'ending_08',
        'title': 'Frenin\'s Visit',
        'title_cn': '弗雷宁的拜访',
        'chapter': 'PART_SEVEN',
        'category': 'friend',
        'description': 'Frenin前来拜访，两人回忆革命岁月',
        'description_cn': '弗雷宁前来拜访，两人回忆革命岁月',
        'characters': ['itale', 'givan_frenin', 'piera'],
        'tags': ['友谊', '回忆', '革命'],
        'evidence': '"We changed the world, didn\'t we?" Frenin said, raising his glass. "We certainly tried," Itale replied.',
        'evidence_cn': '"我们改变了世界，不是吗？"弗雷宁说，举起酒杯。"我们确实努力了，"伊塔勒回答。'
    },
    'ending_09': {
        'id': 'ending_09',
        'title': 'New Generation',
        'title_cn': '新一代',
        'chapter': 'PART_SEVEN',
        'category': 'family',
        'description': 'Itale和Piera有了孩子，新一代在自由世界中成长',
        'description_cn': '伊塔勒和皮耶拉有了孩子，新一代在自由世界中成长',
        'characters': ['itale', 'piera', 'eleonora'],
        'tags': ['孩子', '新一代', '希望'],
        'evidence': 'The children played in the same gardens where Itale had played, but they would grow up in a different world.',
        'evidence_cn': '孩子们在伊塔勒曾玩耍过的相同花园里玩耍，但他们将在一个不同的世界里长大。'
    },
    'ending_10': {
        'id': 'ending_10',
        'title': 'Emanuel\'s Legacy',
        'title_cn': '艾曼纽尔的遗产',
        'chapter': 'PART_SEVEN',
        'category': 'family',
        'description': 'Emanuel去世，Itale继承了他的法律书籍和开明思想',
        'description_cn': '艾曼纽尔去世，伊塔勒继承了他的法律书籍和开明思想',
        'characters': ['itale', 'emanuel', 'perneta'],
        'tags': ['遗产', '思想', '继承'],
        'evidence': 'Emanuel\'s books lined the shelves of Itale\'s study now. His uncle\'s wisdom lived on in him.',
        'evidence_cn': '艾曼纽尔的书现在排列在伊塔勒的书房书架上。他叔叔的智慧在他心中延续。'
    },
    'ending_11': {
        'id': 'ending_11',
        'title': 'The School',
        'title_cn': '学校',
        'chapter': 'PART_SEVEN',
        'category': 'education',
        'description': 'Itale在庄园建立学校，教育农民的孩子',
        'description_cn': '伊塔勒在庄园建立学校，教育农民的孩子',
        'characters': ['itale', 'laura', 'schoolmaster_harmat'],
        'tags': ['教育', '学校', '未来'],
        'evidence': 'The school stood on the edge of the estate, its windows bright with the light of learning.',
        'evidence_cn': '学校矗立在庄园的边缘，它的窗户闪烁着学习的光芒。'
    },
    'ending_12': {
        'id': 'ending_12',
        'title': 'The End of the Journey',
        'title_cn': '旅程的终点',
        'chapter': 'PART_SEVEN',
        'category': 'character',
        'description': 'Itale回顾自己的人生旅程，从年轻理想主义者到成熟的革命者',
        'description_cn': '伊塔勒回顾自己的人生旅程，从年轻理想主义者到成熟的革命者',
        'characters': ['itale', 'piera', 'laura', 'eleonora'],
        'tags': ['回顾', '成熟', '智慧'],
        'evidence': 'He had been young and foolish, brave and reckless, defeated but never broken. And in the end, he had won—not just the revolution, but life itself.',
        'evidence_cn': '他曾经年轻愚蠢，勇敢鲁莽，被打败但从未被摧毁。最后，他赢了——不仅是革命，更是生活本身。'
    }
};

// 章节信息
const chapterData = {
    'PART_ONE': {
        'id': 'PART_ONE',
        'title': '童年与青年',
        'title_en': 'Childhood and Youth',
        'description': 'Itale在Malafrena山谷的成长岁月',
        'color': '#4ECDC4'
    },
    'PART_TWO': {
        'id': 'PART_TWO',
        'title': '城市生活',
        'title_en': 'City Life',
        'description': 'Itale在Malafrena城的大学生活与革命启蒙',
        'color': '#45B7D1'
    },
    'PART_THREE': {
        'id': 'PART_THREE',
        'title': '革命高潮',
        'title_en': 'Revolution Peak',
        'description': '革命运动的兴起与武装起义',
        'color': '#FF6B6B'
    },
    'PART_FOUR': {
        'id': 'PART_FOUR',
        'title': '审判与囚禁',
        'title_en': 'Trial and Imprisonment',
        'description': '革命者的审判、处决和监狱生活',
        'color': '#DDA0DD'
    },
    'PART_FIVE': {
        'id': 'PART_FIVE',
        'title': '逃亡与流亡',
        'title_en': 'Escape and Exile',
        'description': 'Itale越狱逃亡，在流亡中继续革命',
        'color': '#96CEB4'
    },
    'PART_SIX': {
        'id': 'PART_SIX',
        'title': '归来与和解',
        'title_en': 'Return and Reconciliation',
        'description': 'Itale冒险回家，与父亲和解',
        'color': '#FFEAA7'
    },
    'PART_SEVEN': {
        'id': 'PART_SEVEN',
        'title': '结局',
        'title_en': 'The End',
        'description': '革命成功，Itale回归庄园，开始新生活',
        'color': '#FF69B4'
    }
};

// 分类信息
const categoryData = {
    'childhood': {
        'id': 'childhood',
        'name': '童年',
        'color': '#4ECDC4'
    },
    'education': {
        'id': 'education',
        'name': '教育',
        'color': '#45B7D1'
    },
    'family': {
        'id': 'family',
        'name': '家庭',
        'color': '#FF6B6B'
    },
    'romance': {
        'id': 'romance',
        'name': '爱情',
        'color': '#FF69B4'
    },
    'character': {
        'id': 'character',
        'name': '性格',
        'color': '#96CEB4'
    },
    'politics': {
        'id': 'politics',
        'name': '政治',
        'color': '#DDA0DD'
    },
    'action': {
        'id': 'action',
        'name': '行动',
        'color': '#FFEAA7'
    },
    'mystery': {
        'id': 'mystery',
        'name': '神秘',
        'color': '#A8E6CF'
    },
    'arrival': {
        'id': 'arrival',
        'name': '到达',
        'color': '#FFD93D'
    },
    'departure': {
        'id': 'departure',
        'name': '离开',
        'color': '#6C5CE7'
    },
    'mentor': {
        'id': 'mentor',
        'name': '导师',
        'color': '#00B894'
    },
    'social': {
        'id': 'social',
        'name': '社交',
        'color': '#E17055'
    },
    'friend': {
        'id': 'friend',
        'name': '友谊',
        'color': '#0984E3'
    }
};
